### ISSUE TITLE
Can you add the Course-Creator function, Please, Really Need that!!!

### ISSUE THREAD

**Issue by li-xiaojun** [JetBrains/educational-plugin#15]
Hi, I am making a edu product based on idea, and need some help from this plugin. It runs nomally, but I found that  the Course-Creator function is not added or integrated,  Can you add this? Thank you very much!!!

**Comment by medvector** [comment]
Hi!
Actually this plugin already provides course creator functionality.
For which programming language do you need it for? We currently support Python, Java and Kotlin. For Java and Kotlin look to New Project/Education/Create a new course. For Python go to Help -> Enable Course Creator Features and then Create New Course action will appear in File menu.

Could you also please share any details about your product?

**Comment by medvector** [comment]
Hi!

I reproduced the problem with the blank panel. Will fix it soon.

Are you interested in courses for Python or for other languages as well? If you're interested in Python, consider trying PyCharm Edu. (here is the part of documentation about course creation https://www.jetbrains.com/pycharm-edu/educators/).

**Comment by li-xiaojun** [comment]
Ok, I will have a try for PyCharm Edu,  Thank you very much!  
And do you have a plan to support other language, like php, c++, etc...

**Comment by medvector** [comment]
I'm sorry, but not in the nearest future. However, we would be glade to accept a PR with their support :)
