### ISSUE TITLE
Cursor must change on the welcome screen "Are you a Learner or an Educator"

### ISSUE THREAD

**Issue by sskovalevskiy** [JetBrains/educational-plugin#16]
When you hover over a picture of a learner or an educator on the plug-in welcome screen, the cursor should change from the arrow to the cursor-hand. It is not intuitively clear that pictures are buttons.

**Comment by evgraph** [comment]
Hi @sskovalevskiy!

Thanks for reporting this. We created a separate issue in our tracker and it will be fixed soon.
https://youtrack.jetbrains.com/issue/EDU-1316
