### ISSUE TITLE
Section learning

### ISSUE THREAD

**Issue by alfianyusufabdullah** [JetBrains/educational-plugin#23]
Can i put section inside section? like this

--Kotlin First
----Example
-------Example 1
-------Example 2
----Exercise 
-------Exercise 1
-------Exercise 2

**Comment by Geravant** [comment]
@alfianyusufabdullah Hi!
Unfortunately, we do not support nested sections and we are not planning to.
But your structure fits in the Section -> Lesson -> Task model like this:
--Kotlin First (Section)
----Example (Lesson)
-------Example 1 (Task)
-------Example 2 (Task)
----Exercise (Lesson)
-------Exercise 1 (Task)
-------Exercise 2 (Task)
Does it help?

**Comment by alfianyusufabdullah** [comment]
Thanks @Geravant ! saved my day
