### ISSUE TITLE
No documentation on what macros are supported

### ISSUE THREAD

**Issue by mikehearn** [JetBrains/educational-plugin#26]
There's `%IDE_NAME%` but when I went looking for where that came from, I came up blank. What other macros are there, if any?

**Comment by igalimov** [comment]
Hello Mike,
[task.md.zip](https://github.com/JetBrains/educational-plugin/files/4469664/task.md.zip)

**Comment by mikehearn** [comment]
Yes, I read that - that's why I mention `%IDE_NAME%`. Is there only one macro supported?

**Comment by igalimov** [comment]
Yep, this the only one. Also, there's **Insert Shortcut** option.
