### ISSUE TITLE
Not many docs on the "ide" task type

### ISSUE THREAD

**Issue by mikehearn** [JetBrains/educational-plugin#27]
There's a way to teach people how to use the IDE using the "ide" task type, but the docs don't really explain this or how it's different to a theory lesson. It's not really clear to me how to write such tasks.

**Comment by igalimov** [comment]
Hi Mike, it's Ilnur again.
We have more information regarding the different task types in our Educator Start Guide: https://www.jetbrains.com/help/education/educator-start-guide.html?section=Java#create_course.

I'm going to create an article describing our guidelines for the course creators.
And of course, in this article, I'll describe in detail how to create different tasks.

You can track the progress of my work on YouTrack: https://youtrack.jetbrains.com/issue/EDU-3184.

**Comment by mikehearn** [comment]
Great, thanks. I guess some examples of how to teach people how to find buttons/menu items, what they do etc would be good.

**Comment by igalimov** [comment]
Sure, I'll add these details to our documentation. And I'll do my best to make this guide easy to understand and informative.

**Comment by mikehearn** [comment]
Thanks, sounds good.

**Comment by igalimov** [comment]
Good day @mikehearn,

I've added the information regarding IDE tasks into our documentation; please check it out:
https://www.jetbrains.com/help/education/educator-start-guide.html?section=Java#create_course.
It's under step 3.

**Comment by igalimov** [comment]
@mikehearn You can also check out our detailed [guided tour](https://plugins.jetbrains.com/plugin/10081-edutools/docs/guided-tour-around-edutools-ui-a.html) around the EduTools plugin UI.
