### ISSUE TITLE
SBT plugins

### ISSUE THREAD

**Issue by BenFradet** [JetBrains/educational-plugin#29]
Hello,

I'm writing a Scala course using SBT and making use of an SBT plugin in `project/plugins.sbt`.
However, this folder seems to be excluded in

https://github.com/JetBrains/educational-plugin/blob/master/Edu-Scala/src/com/jetbrains/edu/scala/sbt/ScalaSbtConfigurator.kt#L47

Which results in my course preview not compiling.

Would it be possible to not exclude this file?

**Comment by igalimov** [comment]
This issue is currently under investigation: https://youtrack.jetbrains.com/issue/EDU-3753.

**Comment by igalimov** [comment]
The issue has already been fixed; could you please close the issue?
